[tool.poetry]
name = "alphalib"
version = "0.1.0"
description = "A financial investment terminal and library"
authors = ["alpha2phi <alpha2phi@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
rich = "^12.4.1"
investpy = "^1.0.8"
yfinance = "^0.1.70"
backtrader = "^1.9.76"
pydantic = "^1.9.1"
openpyxl = "^3.0.10"
pandas-datareader = "^0.10.0"
fire = "^0.4.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
